services:
  database:
    image: mariadb:lts
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "4406:${MARIADB_PORT}"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PORT=${MARIADB_PORT}
    restart: unless-stopped
  api:
    build: 
      dockerfile: ./docker.php/Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - /app/vendor
      - ./public:/app/public
      - ./src:/app/src
      - ./.php-watcher.yml:/app/.php-watcher.yml
    environment:
      - DB_HOST=database
      - DB_USERNAME=${MARIADB_USER}
      - DB_PASSWORD=${MARIADB_PASSWORD}
      - DB_NAME=${MARIADB_DATABASE}
      - DB_PORT=${MARIADB_PORT}

volumes:
  mariadb_data: