services:
  database:
    image: mariadb:lts
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "4406:${MARIADB_PORT}"
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PORT=${MARIADB_PORT}
    restart: unless-stopped
  api:
    build: 
      dockerfile: ./docker.php/Dockerfile
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./public:/app/public
      - ./src:/app/src

volumes:
  mariadb_data: